package com.app.exceptions;

public enum ExceptionCode {
    VALIDATION,
    GSON,
    CUSTOMER_SERVICE,
    MOVIE_SERVICE,
    SALES_STAND_SERVICE,
    REPOSITORY,
    WRONG_INPUT,
    EMAIL_SERVICE,
    LOYALTY_CARD_REPOSITORY,
    TRANSACTION_HISTORY_SERVICE,
    PROPERTIES_SERVICE,
    MAIN_MENU,
    LOYALTY_CARD_SERVICE
}
