package exceptions;

public enum ExceptionCode {
    GSON,
    CUSTOMER_SERVICE,
    MOVIE_SERVICE,
    SALES_STAND_SERVICE,
    REPOSITORY,
    USER_DATA_SERVICE,
    EMAIL_SERVICE,
    LOYALTY_CARD_REPOSITORY,
    TRANSACTION_HISTORY_SERVICE,
    PROPERTIES_SERVICE,
    LOYALTY_CARD_SERVICE,
    CUSTOMER_REPOSITORY
}
